# grpc config
grpc:
  host: ""
  port: ":9090"
  name: "shop-grpc"

# http config
http:
  host: ""
  port: ":8080"
  name: "shop-http"

pg:
  host: 127.0.0.1
  username: postgres
  password: postgres
  database: postgres
  max-idle-connections: 20
  max-open-connections": 10
  max-connection-life-time-seconds: 600
