// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/superjcd/shopservice/config"
	"github.com/superjcd/shopservice/genproto/v1"
	"github.com/superjcd/shopservice/service"
)

// Injectors from wire.go:

// InitServer Inject service's component
func InitServer(conf *config.Config) (v1.ShopServiceServer, error) {
	shopServiceClient, err := service.NewClient(conf)
	if err != nil {
		return nil, err
	}
	shopServiceServer, err := service.NewServer(conf, shopServiceClient)
	if err != nil {
		return nil, err
	}
	return shopServiceServer, nil
}
